larp/urls.py
from django.conf.urls import patterns, include, url
#from django.contrib import admin

from pages import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'larp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^admin/', include(admin.site.urls)),

    url(r'^groups/', include('plots.groups.urls', namespace="groups")),

    url(r'^personal/your_characters/', 
            include('plots.your_characters.urls', namespace="your_characters")),

    url(r'^GM/', include('plots.GM.urls', namespace='GM')),

    url(r'^$', views.home, name='home'),
    url(r'^new', views.new_top_page, name='new_top_page'),
    url(r'^edit', views.edit_home, name='edit_home'),
    url(r'^page/(?P<id>\d+)/$', views.page, name='page'),
    url(r'^page/(?P<id>\d+)/new$', views.new_subpage, name='new_subpage'),
    url(r'^page/(?P<id>\d+)/edit$', views.edit_page, name='edit_page'),
    url(r'^page/(?P<id>\d+)/delete$', views.delete_page, name='delete_page'),

    url(r'^site_map$', views.sitemap, name='site_map'),

    #url(r'^/', include('pages.urls', namespace='pages')),
    
)
    

plots/GM/urls.py
from django.conf.urls import patterns, url

from plots.GM import views

urlpatterns = [

    # Index
    url(r'^$', views.index, name='index'),

    # Larp/Group/Character
    url(r'^larp_plots/(?P<id>\d+)/$', views.larp_plots, name='larp_plots'),

    url(r'^(?P<class_name>\w+)/(?P<id>\d+)/$', views.edit_topp, name='edit_topp'),
    url(r'^(?P<class_name>\w+)/(?P<id>\d+)/delete/$', views.delete_topp, name='delete_topp'),
    url(r'^(?P<class_name>\w+)/new/$', views.new_topp, name='new_topp'),


    # Plot pice    
    url(r'^larp_plots/(?P<parent_type>\w+)/(?P<parent_id>[0-9]+)/plot_pice/new/$', 
            views.new_plot_pice, name='new_plot_pice'),

    url(r'^larp_plots/(?P<parent_type>\w+)/(?P<parent_id>[0-9]+)/plot_pice/(?P<id>[0-9]+)/$', 
            views.plot_pice, name='plot_pice'),

    url(r'^larp_plots/(?P<parent_type>\w+)/(?P<parent_id>[0-9]+)/plot_pice/(?P<id>[0-9]+)/delete/$', 
            views.delete_plot_pice, name='delete_plot_pice'),

    url(r'^larp_plots/plot_pice/(?P<id>[0-9]+)/$', 
            views.plot_pice_no_parent, name='plot_pice'),


    # Plots
    url(r'^larp_plots/(?P<class_name>\w+)/(?P<id>\d+)/$', views.edit_plots, name='plots' ),
    url(r'^larp_plots/(?P<class_name>\w+)/(?P<id>\d+)/delete/$', views.delete_plots, name='delete_plots' ),
    url(r'^larp_plots/(?P<larp_id>\d+)/(?P<class_name>\w+)/new/$', views.new_plots, name='new_plots' ),
    url(r'^larp_plots/(?P<larp_id>\d+)/(?P<class_name>\w+)/(?P<id>\d+)/$', views.edit_plot_resiver, name='plot_resiver' ),
    url(r'^larp_plots/(?P<larp_id>\d+)/(?P<class_name>\w+)/(?P<id>\d+)/delete$', views.delete_plot_resiver, name='delete_plot_resiver' ),


    


    ]

plots/groups/urls.py
from django.conf.urls import patterns, url

from plots.groups import views

urlpatterns = [

    url(r'^$', views.groups, name='groups'),

    #Groups with odd characters in their names may crach. This should be fixed.
    url(r'^(?P<url>\w+)/$', views.group, name='group') 
]

plots/urls.py
from django.conf.urls import patterns, url

from plots import views

urlpatterns = [

    url(r'^$', views.groups, name='groups'),

    #Groups with odd characters in their names may crach. This should be fixed.
    url(r'^(?P<url>\w+)/$', views.group, name='group') 
]

plots/models.py
from django.db import models
from django.contrib import auth
from django.core import urlresolvers, validators



# Create your models here.

class BasicModel(models.Model):
    class Meta:
        abstract = True
        ordering = ['name']
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name
    def __unicode__(self):          # for Python 2 
        return unicode(self.name)
    


class BasicRelation(models.Model):
    rank = models.FloatField( default=0 )
    rank.help_text = 'Arrange in which order objects appear. Lowest to highest'

    class Meta:
        abstract = True
        ordering = ['rank']

class Membership(BasicRelation):
    character = models.ForeignKey('Character')
    group = models.ForeignKey('Group')
    class Meta(BasicRelation.Meta):
        unique_together = (("group", "character"),)
    former_member = models.BooleanField(default=False)




class BasicPlotRelation(BasicRelation):
    plot_pice = models.ForeignKey('PlotPice')
    class Meta(BasicRelation.Meta):
        abstract = True

class PlotPart(BasicPlotRelation):
    larp_plot_thread = models.ForeignKey('LarpPlotThread')
    class Meta(BasicPlotRelation.Meta):
        unique_together = (("larp_plot_thread", "plot_pice"),)

class GroupPlotPice(BasicPlotRelation):
    group_plot = models.ForeignKey('GroupPlot')
    class Meta(BasicPlotRelation.Meta):
        unique_together = (("group_plot", "plot_pice"),)

class PersonalPlotPice(BasicPlotRelation):
    personal_plot = models.ForeignKey('PersonalPlot')
    class Meta(BasicPlotRelation.Meta):
        unique_together = (("personal_plot", "plot_pice"),)


class GroupPlot(models.Model):
    larp = models.ForeignKey('Larp')
    group = models.ForeignKey('Group')
    class Meta():
        unique_together = (('larp','group'),)

    secret_comments = models.TextField(blank=True, default='')

    plot_is_finished = models.BooleanField(default=False)
    plot_is_finished.verbose_name = "group's plot is finished"

    def name(self):
        return self.group.name

    def __str__(self):
        return self.group.name 
    def __unicode__(self):          # for Python 2 
        return unicode( self.group.name )


class PersonalPlot(models.Model):
    larp = models.ForeignKey('Larp')
    character = models.ForeignKey('Character')
    class Meta():
        unique_together = (('larp','character'),)

    secret_comments = models.TextField(blank=True, default='')

    plot_is_finished = models.BooleanField(default=False)
    plot_is_finished.verbose_name = "character's plot is finished"

    def name(self):
        return self.character.name

    def __str__(self):
        return self.character.name 
    def __unicode__(self):          # for Python 2 
        return unicode( self.character.name )


class LarpPlotThread(models.Model):
    larp = models.ForeignKey('Larp')
    plot_thread = models.ForeignKey('PlotThread')
    class Meta():
        unique_together = (('larp','plot_thread'),)

    plot_is_finished = models.BooleanField(default=False)
    plot_is_finished.verbose_name = "plot thread is finished"

    def name(self):
        return self.plot_thread.name

    def __str__(self):
        return self.plot_thread.name
    def __unicode__(self):          # for Python 2 
        return unicode( self.plot_thread.name )

    def characters(self):
        return PersonalPlot.objects.filter(plotpice__in=self.plot_parts() )
    characters.help_text = (
         'Characters that have part in the plot line, not including group plots')
    characters.short_description = 'Characters involved'
    def characters_string(self):
        return ',\n '.join([character.name for character in self.characters().all()])
    characters_string.help_text = characters.help_text
    characters_string.short_description = characters.short_description
    characters_string.verbose_name = 'characters'

    def groups(self):
        return GroupPlot.objects.filter(plotpice__in=self.plot_parts() )
    groups.help_text = (
        'Groupes that have part in the plot line, not including individual character plots')
    groups.short_description = 'Groupes involved'
    def groups_string(self):
        return ',\n '.join([group.name for group in self.groups().all()])
    groups_string.help_text = groups.help_text
    groups_string.short_description = groups.short_description
    groups_string.verbose_name = 'groups'

    def groups_incl_char(self):
        return GroupPlot.objects.filter(
                    models.Q( plotpice__in=self.plot_parts() ) | 
                    models.Q( character__in=self.characters() )
               ).distinct()        
    groups_incl_char.help_text = (
        'Groupes that have part in the plot line, including individual character plots')
    groups_incl_char.short_description = 'Someone in group is involved'
    groups_incl_char.verbose_name = 'groups incl. personal plots'
    def groups_incl_char_string(self):
        return ',\n '.join([group.name for group in self.groups_incl_char().all()])
    groups_incl_char_string.short_description = groups_incl_char.short_description
    groups_incl_char_string.help_text = groups_incl_char.help_text
    groups_incl_char_string.verbose_name = groups_incl_char.verbose_name



class PlotPice(models.Model):

    def __str__(self):
        return self.plot_pice[0:50]+'...' 
    def __unicode__(self):          # for Python 2 
        return unicode(self.plot_pice[0:50])+'...' 
    __str__.short_description = 'str'

    personal_plots = models.ManyToManyField(
                'PersonalPlot', null=True, blank=True, through='PersonalPlotPice')
    group_plots = models.ManyToManyField(
                'GroupPlot', null=True, blank=True, through='GroupPlotPice')
    larp_plot_threads = models.ManyToManyField( 
                'LarpPlotThread', null=True, blank=True, through='PlotPart')

    plot_pice = models.TextField(blank=True, default='')
    
    plot_is_finished = models.BooleanField(default=False)
    plot_is_finished.verbose_name = 'plot pice is finished'
    plot_is_finished.short_description = 'plot is finished'

    def groups_string(self):
        return ',\n '.join([group.name for group in self.groups.all()])
    groups_string.verbose_name = 'Groups'
    groups_string.short_description = 'Groups'

    def characters_string(self):
        return ',\n '.join([character.name for character in self.characters.all()])
    characters_string.verbose_name = 'Characters'
    characters_string.short_description = 'Characters'

    def plot_threads_string(self):
        return ',\n '.join([plot_thread.name for plot_thread in self.plot_threads.all()])
    plot_threads_string.verbose_name = 'Plot threds'
    plot_threads_string.short_description = 'Plot threds'

    larp = models.ForeignKey('Larp')



class Character(BasicModel):
    
    user = models.ForeignKey(auth.models.User, null=True, blank=True, default=None ) 
    larps = models.ManyToManyField(
                'Larp', null=True, blank=True, through='PersonalPlot') 
    
    def heading(self):
        if self.character_concept == '':
            return self.name
        else: 
            return self.name + ', <small> ' +  self.character_concept + ' </small>'

    
    groups = models.ManyToManyField( 
                'Group', null=True, blank=True, through='Membership')

    character_concept = models.CharField(max_length=50, blank=True)

    presentation = models.TextField(blank=True, default='', max_length=500)
    presentation.help_text = (
        'A short pressentation of the character to be read by all players. Can be written by player or Game Master <br><i>Player can read and write.</i>')

    character_description = models.TextField(blank=True, default='', max_length=5000)
    character_description.help_text = (
        'Character description is usually provided by the player but can also be written by Game Master. Do not change a character description written by a player. <br><i>Player can read and write.</i>')

    other_info = models.TextField(blank=True, default='')

    def groups_string(self):
        return ', '.join([group.name for group in self.groups.all()])
    groups_string.verbose_name = 'Groups'
    groups_string.short_description = 'Groups'
  
  
    
class Group(BasicModel):

    def url(self):
        ret = ''
        for char in self.name:
            if char == ' ':  ret += '_'
            else:           ret += char
        return ret

       
    show_members = models.BooleanField(default=False) 
    show_members.help_text = 'Members presentation is made public.'

    show_group = models.BooleanField(default=False)
    show_group.help_text = 'Group description is made public.'

    is_open = models.BooleanField(default=False)

    group_description = models.TextField(blank=True, default='')
    members_presentations = models.TextField(blank=True, default='')

    characters = models.ManyToManyField(
                'Character', null=True, blank=True, through='Membership')
    characters.verbose_name = "members"

    larps = models.ManyToManyField(
                'Larp', null=True, blank=True, through='GroupPlot' )

    def characters_at_larp(self,larp):
        Character.objects.filter(group=self,larp=larp)

    def personal_plots_at_larp(self,larp):
        PersonalPlot.objects.filter(larp=larp, character__in=self.characters.all() )

    def make_members_presentations(self):
        characters = []
        for member in self.members():
            characters.append( 
                        '<h2>' + member.heading() + '</h2>' +
                        '\n<p>\n' + member.presentation + '\n</p>')

        self.members_presentations = '\n\n'.join( characters )



class PlotThread(BasicModel):
    summery = models.TextField(blank=True, default='')

    larps = models.ManyToManyField( 
                'Larp', null=True, blank=True, through='LarpPlotThread')



class Larp(BasicModel):
    characters = models.ManyToManyField(

plots/groups/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse


from plots.models import Group


def groups(request):
    open_groups = Group.objects.filter(is_open=True).exclude(secret=True)
    if open_groups.count() == 0: 
        open_groups = False
    closed_groups = Group.objects.filter(is_open=False).exclude(secret=True)
    if closed_groups.count() == 0: 
        closed_groups = False
    return render(request, 
                  'plots/groups.html', 
                  {'open_groups': open_groups, 
                   'closed_groups': closed_groups} )



def group(request, url):
    name = ''
    for char in url:
        if char == '_': name += ' '
        else:           name += char

    group = get_object_or_404(Group, name=name)
    if group.secret == True: raise Http404
    return render(request, 'plots/group.html', {'group': group} )

plots/your_characters/views.py
from django.http import Http404, HttpResponseForbidden
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
from django import forms

from plots.models import Character, Group, Membership
from plots import for_views


class YourCharacterFormBasic(forms.ModelForm):
    class Meta:
        model = Character
        fields = [  'name', 
                    'character_concept', 
                    'presentation', 
                    'character_description',
                    'other_info'   ]

def YourCharacterForm(*args, **kw):
    class YourCharacterFormClass(YourCharacterFormBasic):

        groups = for_views.checkboxes( Group.objects.filter(is_open=True) )

        def __init__(self, *args, **kw):
            YourCharacterFormBasic.__init__(self, *args, **kw)
            if kw.has_key('instance'):
                self.fields['groups'].initial = self.instance.groups.filter(is_open=True)
            
        def save(self):
            self.is_valid()
            YourCharacterFormBasic.save(self)
            for_views.save_relations(   self.instance,
                                        Group.objects.filter(is_open=True),
                                        self.instance.groups.filter(is_open=True), 
                                        self.cleaned_data['groups'],
                                        Membership, 'character', 'group' )


    return YourCharacterFormClass(*args, **kw)


def index(request): 
    return render(request, 'plots/your_characters_index.html',
            { 'character_list': Character.objects.filter(user=request.user) }    )


def new(request):
    if request.method == 'POST':
        character_form = YourCharacterForm(request.POST)
        if character_form.is_valid():
            character = Character(user=request.user)
            character.save()
            character_form = YourCharacterForm(request.POST, instance=character )
            character_form.save()
            return HttpResponseRedirect(            
                reverse('your_characters:character', args=(character.id,))  )
    else:
        character_form = YourCharacterForm()

    return render(request, 'plots/your_character_edit.html',
               {'character_form': character_form} )
        

def character(request, id):
    character = get_object_or_404(Character, pk=id)
    if character.user != request.user:
        raise PermissionDenied

    if request.method == 'POST':
        character_form = YourCharacterForm(request.POST, instance=character)
        if character_form.is_valid():
            character_form.save()
    else: 
        character_form = YourCharacterForm(instance=character)     

    return render(request, 'plots/your_character_edit.html',
           {'character_form': character_form}   )     

plots/templates/plots/GM/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}GM{% endblock %}</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'plots/bootstrap.css' %}">
    <script src="{% static 'plots/jquery.js' %}"></script>
    <script src="{% static 'plots/bootstrap.js' %}"></script>
    <script src="{% static 'plots/jquery.sortable.js' %}"></script>


    <style>
        ul.checkboxes_inlie { padding: 0px; }
        ul.checkboxes_inlie li {
            display:inline;
            padding-left: 0px;
            padding-right: 20px;
        }

        textarea { 
            width:100%; 
            /*background-color: #FCE18D;*/
        }

        body {
            /*background-color: #F0AD41;*/
            background-color: #f1eeee;
        }
        
        {% block style %}
        {% endblock %}    

        .my-navbar {
            background-color: #BBF;
        }
        
    </style>
    


    <script>
        $(document).ready(function(){
            {% block script %}
            {% endblock %}
        });   
    </script>

</head>
<body>
WebSiteName 
<div class="larp-title">
  <div class="container-fluid my-navbar">
      <ul class="nav navbar-nav ">
        <li><a href="/">Home</a></li>
        <li><a href="{% url 'GM:index' %}">GM</a></li> 
        {% if larp %}<li><a href="{% url 'GM:larp_plots' larp.id %}">{{ larp.name }}</a></li> {% endif %}
      </ul>
  </div>
</div>



{% block body %}
{% endblock %}

</body>
</html>

plots/templates/plots/GM/basic_form.html
<!DOCTYPE html>

{% extends "plots/GM/basic.html" %}


{% block body %}
<div class="container-fluid">

    {% if class_instance %}
        <h1> {{ class_instance.name }} </h1>
    {% else %}
        <h1> New {{ class_name }} </h1>
    {% endif %}

    <form method="POST" >
        {% csrf_token %}
        {{ class_form.as_p }}
        <p>
            <input type="submit" class="btn btn-default" value="Save" />
            {% if class_instance %}
                <a href="delete" class="btn btn-default"> Delete </a>
            {% endif %}
            {% if larp %}
                <a href="{% url 'GM:larp_plots' larp.id %}" 
                    class="btn btn-default"> Larp overview </a>
            {% else %}
                <a href="{% url 'GM:index' %}" 
                    class="btn btn-default"> GM index </a>
            {% endif %}
        </p>
    </form>
</div>
{% endblock %}

plots/templates/plots/GM/character.html
{% extends "plots/GM/basic.html" %}

{% block body %}

<form method="POST">
{% csrf_token %}
    
    {% if class_instance %}
        <h1> Character: {{ class_instance.name }} </h1>
        <p class="text-danger">Think verry carefylly before changing anything that was written by the player!</p>
    {% else %}
        <h1> New Character </h1>
    {% endif %}

    <table>
        <tr><td>Name: </td><td>{{ class_form.name }}</td></tr>
        <tr><td>Character concept: </td><td> {{ class_form.character_concept }}</td></tr>
    </table>

    <p>
    Character description:<br>
    {{ class_form.character_description }}
    </p>

    <p>
    Other info:<br>
    {{ class_form.other_info }}
    </p>

    <p> 
    Secret comments:<br>
    {{ class_form.secret_comments }}
    </p>

    <input type="submit" value="Save all" />

    <h2>Groups</h2>
    {{ class_form.groups }}

    <input type="submit" value="Save all" />
</form>


{% if id %}
    <p> <a href="{% url 'GM:personal_plot' id %}">
    To Character Plot
    </a> </p>

    <p> <a href="{% url 'GM:delete' 'character' id %}">
    Delete Charactet
    </a> </p>

    <p> <a href="{% url 'GM:new_character' %}">
    New Character
    </a> </p>
{% endif %}

<p> <a href="{% url 'GM:index' %}">
To GM index
</a> </p>

{% endblock %}

plots/templates/plots/GM/index.html
{% extends "plots/GM/basic.html" %}

{% block title %}GM:Index{% endblock %}

{% block body %}

<h1> Larps </h1>
<ul>
    {% for larp in larps %}
    <li>
        <a href="{% url 'GM:edit_topp' 'larp' larp.id %}"> {{ larp.name }} </a> 
        -
        <a href="{% url 'GM:larp_plots' larp.id %}"> Plots </a> 
    </li>
    {% endfor %}
</ul>
<a href="{% url 'GM:new_topp' 'larp' %}" class="btn btn-default"> New larp </a>

<h1> Groups </h1>
<ul>
    {% for group in groups %}
    <li>
        <a href="{% url 'GM:edit_topp' 'group' group.id %}"> {{ group.name }} </a> 
    </li>
    {% endfor %}
</ul>
<a href="{% url 'GM:new_topp' 'group' %}" class="btn btn-default"> New group </a>

<h1> Characters </h1>
<ul>
    {% for character in characters %}
    <li>
        <a href="{% url 'GM:edit_topp' 'character' character.id %}"> {{ character.name }} </a> 
    </li>
    {% endfor %}
</ul>
<a href="{% url 'GM:new_topp' 'character' %}" class="btn btn-default"> New character </a>

<h1> Plot Threads </h1>
<ul>
    {% for plot_thread in plot_threads %}
    <li>
        <a href="{% url 'GM:edit_topp' 'plot_thread' plot_thread.id %}"> {{ plot_thread.name }} </a> 
    </li>
    {% endfor %}
</ul>
<a href="{% url 'GM:new_topp' 'plot_thread' %}" class="btn btn-default"> New plot thread </a>


{% endblock %}

plots/templates/plots/GM/larp_plots.html
{% extends "plots/GM/basic.html" %}

{% block title %}GM:{{ larp.name }}{% endblock %}

{% block body %}

<h1> Plot threads <small>(<a href="{% url 'GM:new_plots' larp.id 'plot_thread' %}">New</a>)</small></h1>

<ul>
{% for larp_plot_thread in larp.larpplotthread_set.all %} 
    <li>
        <a href="{% url 'GM:plots' 'larp_plot_thread' larp_plot_thread.id %}"> 
        {{ larp_plot_thread.name }} </a> 
    </li>
{% endfor %}
</ul>


<h3> Plot Pices without Character or Group </h3>
{% if larp.plot_pices_with_no_character_or_group %}
    <ul>
    {% for plot_pice in larp.plot_pices_with_no_character_or_group %} 
        <li>
        <a href="{% url 'GM:plot_pice' plot_pice.id %}"> 
        {{ plot_pice }} </a> 
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no such plot pices.</p>
{% endif %}

<h3> Plot Pices without Plot Thread </h3>
{% if larp.plot_pices_with_no_plot_thread %}
    <ul>
    {% for plot_pice in larp.plot_pices_with_no_plot_thread %} 
        <li>
        <a href="{% url 'GM:plot_pice' plot_pice.id %}"> 
        {{ plot_pice }} </a> 
        </li>
    {% endfor %}
    </ul>
{% else %}
    <p>There are no such plot pices.</p>
{% endif %}



<h1> 
    Groups 
    <small>
        (<a href="{% url 'GM:new_plots' larp.id 'group' %}">New</a>)
    </small> 
</h1>
<ul>
    {% for group_plot in larp.groupplot_set.all %} 
    <li>
        <a href="{% url 'GM:plot_resiver' larp.id 'group' group_plot.group.id %}">
        {{ group_plot.group.name }} </a>
        -
        <a href="{% url 'GM:plots' 'group_plot' group_plot.id %}">Plot</a>
    </li>
    {% endfor %}
</ul> 


<h1> Characters 
    <small>
        (<a href="{% url 'GM:new_plots' larp.id 'character' %}">New</a>)
    </small> 
</h1>

{% for group in larp.groupplot_set.all %}
<h3> {{ group }} </h3>

<ul>
    {% for character in group.personal_plot_at_larp(larp) %}
    <li>
        <a href="{% url 'GM:plot_resiver' larp.id 'character' personal_plot.character.id %}"> 
        {{ personal_plot.character.name }}</a>
        -
        <a href="{% url 'GM:plots' 'personal_plot' personal_plot.id %}">Plot</a>
    </li>
    {% endfor %}
</ul> 
{% endfor %}

{% endblock %}

plots/templates/plots/GM/members.html
{% extends "plots/GM/basic.html" %}

{% block body %}

    <h1> {{ group.name }}, Members </h1>

    <form method="POST" >
        {% csrf_token %}
        {{ members_form.characters }}

        <input type="submit" value="Save" />
    </form>

    <p> <a href="{% url 'GM:index' %}">
    Cancel
    </a> </p>

{% endblock %}

plots/templates/plots/GM/personal_plot.html
{% extends "plots/GM/plots.html" %}


{% block top %}

    <h1> Personal plot for: {{ class_instance.name }} </h1>
    
    <p>
    Character description:<br>
    {{ class_form.character_description }}
    </p>
    
    <p>
    Other info:<br>
    {{ class_form.other_info }}
    </p>

    <p> 
    Secret comments:<br>
    {{ class_form.secret_comments }}
    </p>

    <p>
    Plot thread is finished: {{ class_form.plot_is_finished }}
    </p>
    
    <input type="submit" value="Save all" />
    <a href="{% url 'GM:character' class_instance.id %}"> Edit character </a>

    <h2> Groups </h2>
    {% for group in class_instance.groups.all %}
        <a href="{% url 'GM:group_plot' group.id %}">{{ group.name }}</a><br>
    {% endfor %}

{% endblock %}

plots/templates/plots/GM/plot_pice.html
{% extends "plots/GM/basic.html" %}

{% block body %}


<h1> {{ heading }} Plot Pice </h1>


<form method="POST" >
    {% csrf_token %}
    <p>{{ plot_pice_form.plot_pice }}</p>
    <p><b> Plot Pice is finnished: </b> {{ plot_pice_form.plot_is_finished }}</p>

    <h3> Plot Threads </h3>
    {{ plot_pice_form.larp_plot_threads }}
    <b>New:</b> {{ plot_pice_form.new_plot_thread_name}}

    <h3> Groups </h3>
    {{ plot_pice_form.group_plots }}
    <b>New:</b> {{ plot_pice_form.new_group_name }}

    <h3> Characters </h3>
    {{ plot_pice_form.personal_plots }}
    <b>New:</b> {{ plot_pice_form.new_character_name }}

    <p> <input type="submit" value="Save" /> </p>
</form> 


<p> <a href="delete"> Delete </a> </p>

<p> <a href="{{ back }}"> Cancel </a> </p>



{% endblock %}

plots/templates/plots/GM/plot_thread.html
{% extends "plots/GM/plots.html" %}


{% block menue %}
    <a href="delete" class="btn btn-default"> Delete </a>
{% endblock %}


{% block display %}
    <h2> Groups involved <small>(not including personal plots)</small> </h2>
    <ul>    
    {% for group in class_instance.groups %}
        <li>
        <a href="{% url 'GM:group_plot' group.id %}"> {{ group.name }} </a>
        </li>
    {% endfor %}
    </ul>

    <h2> Groups involved <small>(including personal plots)</small> </h2>
    <ul>
    {% for group in class_instance.groups_incl_char %}
        <li>
        <a href="{% url 'GM:group_plot' group.id %}"> {{ group.name }} </a>
        </li>
    {% endfor %}
    </ul>

    <h2> Characters involved <small>(not including group plots)</small> </h2>
    <ul>
    {% for character in class_instance.characters %}
        <li>
        <a href="{% url 'GM:personal_plot' character.id %}"> {{ character.name }} </a>
        </li>
    {% endfor %}
    </ul>
{% endblock %}