larp/urls.py
from django.conf.urls import patterns, include, url
#from django.contrib import admin

from pages import views


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'larp.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    #url(r'^admin/', include(admin.site.urls)),

    url(r'^groups/', include('plots.groups.urls', namespace="groups")),

    url(r'^personal/your_characters/', 
            include('plots.your_characters.urls', namespace="your_characters")),

    url(r'^GM/', include('plots.GM.urls', namespace='GM')),

    url(r'^$', views.home, name='home'),
    url(r'^new', views.new_top_page, name='new_top_page'),
    url(r'^edit', views.edit_home, name='edit_home'),
    url(r'^page/(?P<id>\d+)/$', views.page, name='page'),
    url(r'^page/(?P<id>\d+)/new$', views.new_subpage, name='new_subpage'),
    url(r'^page/(?P<id>\d+)/edit$', views.edit_page, name='edit_page'),
    url(r'^page/(?P<id>\d+)/delete$', views.delete_page, name='delete_page'),

    url(r'^site_map$', views.sitemap, name='site_map'),

    #url(r'^/', include('pages.urls', namespace='pages')),
    
)
    

plots/GM/urls.py
from django.conf.urls import patterns, url

from plots.GM import views

urlpatterns = [

    # Index
    url(r'^$', views.index, name='index'),

    # Larp/Group/Character
    url(r'^larp_plots/(?P<id>\d+)/$', views.larp_plots, name='larp_plots'),

    url(r'^(?P<class_name>\w+)/(?P<id>\d+)/$', views.edit_topp, name='edit_topp'),
    url(r'^(?P<class_name>\w+)/(?P<id>\d+)/delete/$', views.delete_topp, name='delete_topp'),
    url(r'^(?P<class_name>\w+)/new/$', views.new_topp, name='new_topp'),


    # Plot pice    
    url(r'^larp_plots/(?P<parent_type>\w+)/(?P<parent_id>[0-9]+)/plot_pice/new/$', 
            views.new_plot_pice, name='new_plot_pice'),

    url(r'^larp_plots/(?P<parent_type>\w+)/(?P<parent_id>[0-9]+)/plot_pice/(?P<id>[0-9]+)/$', 
            views.plot_pice, name='plot_pice'),

    url(r'^larp_plots/(?P<parent_type>\w+)/(?P<parent_id>[0-9]+)/plot_pice/(?P<id>[0-9]+)/delete/$', 
            views.delete_plot_pice, name='delete_plot_pice'),

    url(r'^larp_plots/plot_pice/(?P<id>[0-9]+)/$', 
            views.plot_pice_no_parent, name='plot_pice'),


    # Plots
    url(r'^larp_plots/(?P<class_name>\w+)/(?P<id>\d+)/$', views.edit_plots, name='plots' ),
    url(r'^larp_plots/(?P<class_name>\w+)/(?P<id>\d+)/delete/$', views.delete_plots, name='delete_plots' ),
    url(r'^larp_plots/(?P<larp_id>\d+)/(?P<class_name>\w+)/new/$', views.new_plots, name='new_plots' ),
    url(r'^larp_plots/(?P<larp_id>\d+)/(?P<class_name>\w+)/(?P<id>\d+)/$', views.edit_plot_resiver, name='plot_resiver' ),
    url(r'^larp_plots/(?P<larp_id>\d+)/(?P<class_name>\w+)/(?P<id>\d+)/delete$', views.delete_plot_resiver, name='delete_plot_resiver' ),


    


    ]

pages/models.py
from django.db import models
import plots.models as plots

# Create your models here.


initial_html = u'''<p>
Fist paragraph... 
</p>

<p>
Second paragraph...
</p>

<h2> Sub-title </h2>
<p>
Evem more text...
</p>'''

class Page(models.Model):
    class Meta:
        ordering = ['title']

    title = models.CharField(max_length=50)
    def __str__(self):
        return self.title
    def __unicode__(self):          # for Python 2 
        return unicode(self.title)

    top_page = models.BooleanField(default=True)
    sort_under = models.ForeignKey('Page', null=True, blank=True, on_delete=models.SET_NULL)
    sort_under_group = models.ForeignKey('plots.Group', null=True, blank=True, on_delete=models.SET_NULL)
    sort_under_larp = models.ForeignKey('plots.Larp', null=True, blank=True, on_delete=models.SET_NULL)
    html = models.TextField(blank=True, default='')
    

class Home(models.Model):
    title = models.CharField(max_length=50, default='WebSiteName')
    def __str__(self):
        return self.title
    def __unicode__(self):          # for Python 2 
        return unicode(self.title)

    html = models.TextField(blank=True, default=initial_html)

pages/templates/pages/edit_page.html
{% extends "pages/page.html" %}

{% block body %}
    <form method="POST" >
        {% csrf_token %}
        {{ page_form.as_p }}
        <p>
            <input type="submit" class="btn btn-default" value="Save" />

            <a {% if id %} href="{% url 'page' id %}" {% else %} href="{% url 'home' %}" {% endif %}
                class="btn btn-default" > Cancel </a>

            <input type="reset" class="btn btn-default" value="Reset" />

            {% if delete %}
            <a href="delete" class="btn btn-default" 
                onclick="return confirm('Are you sure you want to delete this page?');"> 
                Delete </a>
            {% endif %}
        </p>
    </form>
{% endblock %}

pages/templates/pages/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>WebSiteName</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
    -->
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'plots/bootstrap.css' %}">
    <script src="{% static 'plots/jquery.js' %}"></script>
    <script src="{% static 'plots/bootstrap.js' %}"></script>
    <script src="{% static 'plots/jquery.sortable.js' %}"></script>
    
    <style>
        textarea { 
            width:100%; 
        }
    </style>


</head>
<body>
<div class="container-fluid">
    {{ top_logo }} 
</div>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
      <ul class="nav navbar-nav ">
        <li><a href="/">Home</a></li>

        {% for nav_item in nav_list %}
        <li><a href="{% url 'page' nav_item.id %}">{{ nav_item.title }}</a></li> 
        {% endfor %}

        <li><a href="{% url 'site_map' %}">Site Map</a></li> 

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">GM
          <span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if edit %}<li><a href="edit">Edit/Delete this page</a></li>{% endif %}
            <li><a href="new">Add new page</a></li>
            <li><a href="{% url 'GM:index' %}">GM index</a></li> 
          </ul>
        </li>

      </ul>
  </div>
</nav>


<div class="container-fluid">
    {{ my_error_message }}
    {% block body %}
        <h1>
            {% if title %}{{ title }}
            {% elif page.title %}{{ page.title }}
            {% else %}WebSiteName{% endif %}
        </h1>
        {{ page.html|safe }}
        {{ html|safe }}
        <ul>
        {% for subpage in page.page_set.all %}
            <li><a href="{% url 'page' subpage.id %}">{{ subpage.title }}</a></li>
        {% endfor %}
        </ul>
    {% endblock %}    
</div>


</body>
</html>